steps:
  - command: .buildkite/scripts/steps/functional/apm_cypress.sh
    cancel_on_build_failing: true
    label: 'APM Cypress Tests'
    agents:
      machineType: n2-standard-4
      preemptible: true
      spotZones: us-central1-f,us-central1-c,us-central1-a
    depends_on:
      - build
    timeout_in_minutes: 60
    parallelism: 3
    retry:
      automatic:
        - exit_status: '-1'
          limit: 3
        - exit_status: '*'
          limit: 1
