steps:
  - command: .buildkite/scripts/steps/build_kibana.sh
    cancel_on_build_failing: true
    label: Build Kibana Distribution
    agents:
      machineType: c4d-standard-16
      diskType: hyperdisk-balanced
      preemptible: true
      spotZones: us-central1-c,us-central1-a
      diskSizeGb: 200
    key: build
    if: "build.env('KIBANA_BUILD_ID') == null || build.env('KIBANA_BUILD_ID') == ''"
    timeout_in_minutes: 60
    retry:
      automatic:
        - exit_status: '-1'
          limit: 3

  - command: .buildkite/scripts/steps/quick_checks.sh
    cancel_on_build_failing: true
    label: 'Quick Checks'
    agents:
      machineType: c4d-standard-8
      diskType: hyperdisk-balanced
      preemptible: true
      spotZones: us-central1-c,us-central1-a
      diskSizeGb: 105
    key: quick_checks
    timeout_in_minutes: 60
    retry:
      automatic:
        - exit_status: '-1'
          limit: 3

  - command: .buildkite/scripts/steps/checks.sh
    cancel_on_build_failing: true
    label: 'Checks'
    agents:
      machineType: c4d-standard-2
      diskType: hyperdisk-balanced
      preemptible: true
      spotZones: us-central1-c,us-central1-a
      diskSizeGb: 105
    timeout_in_minutes: 60
    key: checks
    retry:
      automatic:
        - exit_status: '-1'
          limit: 3

  - command: .buildkite/scripts/steps/lint.sh
    cancel_on_build_failing: true
    label: 'Linting'
    agents:
      machineType: c4d-standard-16
      diskType: hyperdisk-balanced
      preemptible: true
      spotZones: us-central1-c,us-central1-a
      diskSizeGb: 105
    key: linting
    timeout_in_minutes: 60
    retry:
      automatic:
        - exit_status: '-1'
          limit: 3

  - command: .buildkite/scripts/steps/lint_with_types.sh
    cancel_on_build_failing: true
    label: 'Linting (with types)'
    agents:
      machineType: c4d-standard-32
      diskType: hyperdisk-balanced
      preemptible: true
      spotZones: us-central1-c,us-central1-a
      diskSizeGb: 105
    key: linting_with_types
    timeout_in_minutes: 60
    retry:
      automatic:
        - exit_status: '-1'
          limit: 3

  - command: .buildkite/scripts/steps/checks/capture_oas_snapshot.sh
    cancel_on_build_failing: true
    label: 'Check OAS Snapshot'
    agents:
      machineType: c4d-standard-2
      diskType: hyperdisk-balanced
      preemptible: true
      spotZones: us-central1-c,us-central1-a
    key: check_oas_snapshot
    timeout_in_minutes: 60
    retry:
      automatic:
        - exit_status: '-1'
          limit: 3

  - command: .buildkite/scripts/steps/typecheck/check_types.sh
    cancel_on_build_failing: true
    label: 'Check Types'
    agents:
      machineType: c4d-highmem-4
      diskType: hyperdisk-balanced
      preemptible: true
      spotZones: us-central1-c,us-central1-a
      diskSizeGb: 105
    key: check_types
    timeout_in_minutes: 60
    retry:
      automatic:
        - exit_status: '-1'
          limit: 3

  - command: .buildkite/scripts/steps/test/pick_test_group_run_order.sh
    cancel_on_build_failing: true
    label: 'Pick Test Group Run Order'
    agents:
      machineType: n2-standard-2
      diskSizeGb: 115
    timeout_in_minutes: 10
    env:
      JEST_UNIT_SCRIPT: '.buildkite/scripts/steps/test/jest.sh'
      JEST_INTEGRATION_SCRIPT: '.buildkite/scripts/steps/test/jest_integration.sh'
      FTR_CONFIGS_SCRIPT: '.buildkite/scripts/steps/test/ftr_configs.sh'
      FTR_CONFIGS_DEPS: 'build'
    retry:
      automatic:
        - exit_status: '*'
          limit: 1

  - command: .buildkite/scripts/steps/test/scout/test_run_builder.sh
    cancel_on_build_failing: true
    label: 'Scout Test Run Builder'
    agents:
      machineType: n2d-standard-8
    key: build_scout_tests
    timeout_in_minutes: 20
    depends_on:
      - build
    env:
      SCOUT_CONFIGS_DEPS: 'build_scout_tests'
      SCOUT_CONFIGS_SCRIPT: '.buildkite/scripts/steps/test/scout/configs.sh'
    retry:
      automatic:
        - exit_status: '*'
          limit: 1

  - command: .buildkite/scripts/steps/ci_stats_ready.sh
    cancel_on_build_failing: true
    label: Mark CI Stats as ready
    agents:
      machineType: n2-standard-2
    timeout_in_minutes: 10
    depends_on:
      - build
      - build_api_docs
    retry:
      automatic:
        - exit_status: '*'
          limit: 1

  - command: .buildkite/scripts/steps/api_docs/build_api_docs.sh
    cancel_on_build_failing: true
    label: 'Build API Docs'
    agents:
      machineType: n2-highmem-4
      preemptible: true
      spotZones: us-central1-f,us-central1-c,us-central1-a
      diskSizeGb: 105
    key: build_api_docs
    depends_on:
      - build
    timeout_in_minutes: 60
    retry:
      automatic:
        - exit_status: '-1'
          limit: 3
