steps:
  - command: .buildkite/scripts/steps/artifacts/docker_image.sh
    cancel_on_build_failing: true
    label: 'Build Project Image'
    key: build_project_image
    agents:
      machineType: n2-standard-16
      preemptible: true
      diskSizeGb: 150
    timeout_in_minutes: 90
    retry:
      automatic:
        - exit_status: '-1'
          limit: 3
  - command: .buildkite/scripts/steps/serverless/deploy.sh
    cancel_on_build_failing: true
    label: 'Deploy Project'
    agents:
      machineType: n2-standard-4
      preemptible: true
    timeout_in_minutes: 10
    depends_on:
      - build_project_image
    retry:
      automatic:
        - exit_status: '-1'
          limit: 3
