steps:
  - command: .buildkite/scripts/steps/cloud/build_and_deploy.sh
    cancel_on_build_failing: true
    label: 'Build and Deploy to Cloud'
    agents:
      machineType: n2-standard-2
      preemptible: true
    depends_on:
      - build
    timeout_in_minutes: 30
    soft_fail: true
    retry:
      automatic:
        - exit_status: '-1'
          limit: 3
