steps:
  - command: .buildkite/scripts/steps/jest_bench.sh
    cancel_on_build_failing: true
    label: 'Jest Bench'
    agents:
      machineType: c4d-standard-16
      diskType: hyperdisk-balanced
      zones: us-central1-c,us-central1-a
      diskSizeGb: 100
    key: jest_bench
    timeout_in_minutes: 60
    soft_fail: true
