steps:
  - command: .buildkite/scripts/steps/renovate.sh
    cancel_on_build_failing: true
    label: 'Renovate validation'
    agents:
      machineType: n2-highcpu-8
      preemptible: true
      spotZones: us-central1-f,us-central1-c,us-central1-a
    key: renovate_validation
    timeout_in_minutes: 60
    retry:
      automatic:
        - exit_status: '-1'
          limit: 3
