steps:
  - command: .buildkite/scripts/steps/functional/cloud_security_posture.sh
    cancel_on_build_failing: true
    label: 'Cloud Security Posture Cypress Tests'
    agents:
      machineType: n2-standard-4
      preemptible: true
      spotZones: us-central1-f,us-central1-c,us-central1-a
    depends_on:
      - build
    timeout_in_minutes: 60
    parallelism: 1
    retry:
      automatic:
        - exit_status: '-1'
          limit: 1

  - command: .buildkite/scripts/steps/functional/cloud_security_posture_serverless.sh
    cancel_on_build_failing: true
    label: 'Cloud Security Posture Cypress Tests on Serverless'
    agents:
      machineType: n2-standard-4
      preemptible: true
      spotZones: us-central1-f,us-central1-c,us-central1-a
    depends_on:
      - build
    timeout_in_minutes: 60
    parallelism: 1
    retry:
      automatic:
        - exit_status: '-1'
          limit: 1
