steps:
  - command: .buildkite/scripts/steps/functional/security_solution_investigations.sh
    label: 'Investigations - Security Solution Cypress Tests'
    agents:
      machineType: n2-standard-4
      preemptible: true
      spotZones: us-central1-f,us-central1-c,us-central1-a
    depends_on:
      - build
    timeout_in_minutes: 60
    parallelism: 9
    retry:
      automatic:
        - exit_status: '-1'
          limit: 1

  - command: .buildkite/scripts/steps/functional/security_serverless_investigations.sh
    label: 'Serverless Investigations - Security Solution Cypress Tests'
    agents:
      machineType: n2-standard-4
      preemptible: true
      spotZones: us-central1-f,us-central1-c,us-central1-a
    depends_on:
      - build
    timeout_in_minutes: 60
    parallelism: 11
    retry:
      automatic:
        - exit_status: '-1'
          limit: 1
